services:
  postgres:
    container_name: big_chat_postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=big_chat_db

  app:
    container_name: big_chat_app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres


