spring:
  application:
    name: big-chat-brasil
  datasource:
    url: jdbc:postgresql://localhost:5432/big_chat_db
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/master.xml

server:
  port: 8080
  servlet:
    context-path: "/api"
  error:
    include-stacktrace: never

security:
  token:
    secret:
      cliente: "cliente_secret_prod"

