spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/big_chat_db
  config:
    activate:
      on-profile: dev
  liquibase:
    contexts: dev

security:
  token:
    secret:
      cliente: "cliente_secret_dev"
